[build]
builder = "nixpacks"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"

[variables]
USE_REAL_DATA = "false"
PYTHONPATH = "/app"
DATABASE_URL = "sqlite+aiosqlite:///./infrasight.db"
SECRET_KEY = "deployment-secret-key-change-in-production"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = "30"
